@extends('layouts.app')
@section('content')
<section class="space-y-4">
    <h1 class="text-2xl font-black">وارد کردن داده</h1>
    <form method="post" enctype="multipart/form-data" action="{{ route('imports.csv') }}" class="glass space-y-3 rounded-3xl p-4">@csrf<h2 class="font-black">CSV / Excel بانک</h2><input name="statement" type="file" class="tap w-full"><button class="tap rounded-2xl bg-slate-950 px-4 font-bold text-white">ارسال فایل</button></form>
    <form method="post" action="{{ route('imports.sms-preview') }}" class="glass space-y-3 rounded-3xl p-4">@csrf<h2 class="font-black">پیش‌نمایش پیامک بانکی</h2><select name="sms_pattern_id" class="tap w-full rounded-2xl border-0 bg-white/90 px-4 dark:bg-slate-800"><option value="">تشخیص خودکار</option>@foreach($smsPatterns as $pattern)<option value="{{ $pattern->id }}">{{ $pattern->name }}</option>@endforeach</select><textarea name="sms_text" class="min-h-32 w-full rounded-2xl border-0 bg-white/90 px-4 py-3 dark:bg-slate-800" placeholder="متن پیامک را اینجا بچسبانید"></textarea><button class="tap rounded-2xl bg-slate-950 px-4 font-bold text-white">تحلیل پیامک</button></form>
    <form method="post" action="{{ route('imports.sms-patterns.store') }}" class="glass space-y-3 rounded-3xl p-4">@csrf<h2 class="font-black">الگوی پیامک بانک</h2><input name="name" placeholder="نام الگو" class="tap w-full rounded-2xl border-0 bg-white/90 px-4 dark:bg-slate-800"><input name="bank_name" placeholder="نام بانک" class="tap w-full rounded-2xl border-0 bg-white/90 px-4 dark:bg-slate-800"><textarea name="pattern" class="min-h-28 w-full rounded-2xl border-0 bg-white/90 px-4 py-3 font-mono text-sm ltr:text-left dark:bg-slate-800" placeholder="Regex با گروه‌های amount، type، balance، date، card"></textarea><input name="debit_keywords" placeholder="کلیدواژه‌های برداشت، جدا با ویرگول" class="tap w-full rounded-2xl border-0 bg-white/90 px-4 dark:bg-slate-800"><input name="credit_keywords" placeholder="کلیدواژه‌های واریز، جدا با ویرگول" class="tap w-full rounded-2xl border-0 bg-white/90 px-4 dark:bg-slate-800"><button class="tap rounded-2xl bg-slate-950 px-4 font-bold text-white">ذخیره الگو</button></form>
    <div class="space-y-2">@foreach($smsPatterns as $pattern)<div class="rounded-3xl bg-white/85 p-4 dark:bg-slate-900"><strong>{{ $pattern->name }}</strong><p class="mt-1 text-xs text-slate-500">{{ $pattern->bank_name ?: 'بدون بانک' }}</p></div>@endforeach</div>
</section>
@endsection
